version: "2.4"
services:
  mgt01:
    image: weizhouapache/cloudstack-management
    hostname: mgt01
    networks:
      cloudstack:
        ipv4_address: 10.0.34.4

networks:
  cloudstack:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "10.0.32.0/20"
          gateway: "10.0.32.1"  
