version: "2.4"
services:
  mgt01:
    image: ubuntu:22.04
    hostname: mgt01
    networks:
      cs:
        ipv4_address: 10.0.34.217
    entrypoint: ["tail", "-f", "/dev/null"]
    expose:
      - 8250
      - 8080
      - 8096
      - 22

networks:
  cs:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "10.0.32.0/20"
          gateway: "10.0.32.1"  
