services:
  db01:
    image: ustcweizhou/mariadb-cluster:latest
    hostname: db01
    networks:
        cs-net:
            ipv4_address: 172.19.24.11
    volumes:
      - ./db01:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin", "-uroot", "-pcloudstack", "ping"]
        interval: 5s
        timeout: 10s
        retries: 60
        start_period: 10s
    environment:
      - NODE_NAME=db01
      - CLUSTER_ADDRESS=gcomm://db01,db02,db03
      - DB_ROOT_PASSWORD=cloudstack
      - DB_MARIABACKUP_PASSWORD=cloudstack

  db02:
    image: ustcweizhou/mariadb-cluster:latest
    hostname: db02
    depends_on:
        db01:
            condition: service_healthy
    networks:
        cs-net:
            ipv4_address: 172.19.24.12
    volumes:
      - ./db02:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin", "-uroot", "-pcloudstack", "ping"]
        interval: 5s
        timeout: 10s
        retries: 60
        start_period: 10s
    environment:
      - NODE_NAME=db02
      - CLUSTER_ADDRESS=gcomm://db01,db02,db03
      - DB_ROOT_PASSWORD=cloudstack
      - DB_MARIABACKUP_PASSWORD=cloudstack

  db03:
    image: ustcweizhou/mariadb-cluster:latest
    hostname: db03
    depends_on:
        db01:
            condition: service_healthy
        db02:
            condition: service_healthy
    networks:
        cs-net:
            ipv4_address: 172.19.24.13
    volumes:
      - ./db03:/var/lib/mysql
    environment:
      - NODE_NAME=db03
      - CLUSTER_ADDRESS=gcomm://db01,db02,db03
      - DB_ROOT_PASSWORD=cloudstack
      - DB_MARIABACKUP_PASSWORD=cloudstack

  dbvip:
    image: nginx
    hostname: dbvip
    networks:
        cs-net:
            ipv4_address: 172.19.24.14
    ports:
        - "13324:3306"
    volumes:
      - ./nginx-galera-cs24.conf:/etc/nginx/nginx.conf
    depends_on:
        db01:
            condition: service_healthy

  mgt01:
    image: weizhouapache/cloudstack-management:latest
    hostname: mgt01
    privileged: true
    networks:
        cs-net:
            ipv4_address: 172.19.24.20
    ports:
        - "18080:8080"
        - "18250:8250"
        - "18096:8096"
    depends_on:
        db01:
            condition: service_healthy

networks:
    cs-net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.19.24.0/24
                  gateway: 172.19.24.254
